### ISSUE TITLE
Filter with empty value

### ISSUE THREAD

**Issue by rauwebieten** [horlyk/fetch-xml-bundle#1]
When adding a filter with a empty string as value, it is not rendered in the fetchXML query.
(which causes an exception on the database server)

Code:
`$queryBuilder->addFilter(new Filter('field','','ne'))`

Expected result:
`<condition attribute="field" operator="ne" value="" />`

Result:
`<condition attribute="field" operator="ne"  />`

**Comment by horlyk** [comment]
@rauwebieten new release of 1.5.0 is done. Thanks for contributing 👍
